tenets:
  - name: well-formed-lists
    flows:
      codelingo/docs:
        title: Well Formed Lists
        body: |
          All lists use the required `items` field to contain the array of objects they return.
      codelingo/review:
        comment: This is a list and must contain an `items` field.
    query: |
      import codelingo/ast/go
      
      go.decls:
        go.gen_decl:
          go.type_spec:
            @review comment
            go.ident:
              name as listName
            go.struct_type:
              go.field_list:
                go.field:
                  go.selector_expr:
                    go.ident:
                      name == "metav1"
                    go.ident:
                      name == "TypeMeta"
                go.field:
                  go.selector_expr:
                    go.ident:
                      name == "metav1"
                    go.ident:
                      name == "ListMeta"
                exclude:
                  go.field:
                    go.names:
                      go.ident:
                        name == "Items"
