// Code generated by protoc-gen-go.
// source: github.com/codelingo/codelingo/flows/codelingo/rewrite/rpc/rewrite.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	github.com/codelingo/codelingo/flows/codelingo/rewrite/rpc/rewrite.proto

It has these top-level messages:
	Request
	Hunk
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the files or directories to review.
type Request struct {
	Host     string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Hostname string `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	// Types that are valid to be assigned to OwnerOrDepot:
	//	*Request_Owner
	//	*Request_Depot
	OwnerOrDepot  isRequest_OwnerOrDepot `protobuf_oneof:"ownerOrDepot"`
	Repo          string                 `protobuf:"bytes,4,opt,name=repo" json:"repo,omitempty"`
	Sha           string                 `protobuf:"bytes,5,opt,name=sha" json:"sha,omitempty"`
	Patches       []string               `protobuf:"bytes,6,rep,name=Patches" json:"Patches,omitempty"`
	IsPullRequest bool                   `protobuf:"varint,7,opt,name=isPullRequest" json:"isPullRequest,omitempty"`
	PullRequestID int64                  `protobuf:"varint,8,opt,name=pullRequestID" json:"pullRequestID,omitempty"`
	Vcs           string                 `protobuf:"bytes,9,opt,name=vcs" json:"vcs,omitempty"`
	Dotlingo      string                 `protobuf:"bytes,10,opt,name=dotlingo" json:"dotlingo,omitempty"`
	Dir           string                 `protobuf:"bytes,11,opt,name=dir" json:"dir,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isRequest_OwnerOrDepot interface {
	isRequest_OwnerOrDepot()
}

type Request_Owner struct {
	Owner string `protobuf:"bytes,12,opt,name=owner,oneof"`
}
type Request_Depot struct {
	Depot string `protobuf:"bytes,13,opt,name=depot,oneof"`
}

func (*Request_Owner) isRequest_OwnerOrDepot() {}
func (*Request_Depot) isRequest_OwnerOrDepot() {}

func (m *Request) GetOwnerOrDepot() isRequest_OwnerOrDepot {
	if m != nil {
		return m.OwnerOrDepot
	}
	return nil
}

func (m *Request) GetOwner() string {
	if x, ok := m.GetOwnerOrDepot().(*Request_Owner); ok {
		return x.Owner
	}
	return ""
}

func (m *Request) GetDepot() string {
	if x, ok := m.GetOwnerOrDepot().(*Request_Depot); ok {
		return x.Depot
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_Owner)(nil),
		(*Request_Depot)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// ownerOrDepot
	switch x := m.OwnerOrDepot.(type) {
	case *Request_Owner:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Owner)
	case *Request_Depot:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Depot)
	case nil:
	default:
		return fmt.Errorf("Request.OwnerOrDepot has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 12: // ownerOrDepot.owner
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OwnerOrDepot = &Request_Owner{x}
		return true, err
	case 13: // ownerOrDepot.depot
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OwnerOrDepot = &Request_Depot{x}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// ownerOrDepot
	switch x := m.OwnerOrDepot.(type) {
	case *Request_Owner:
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Owner)))
		n += len(x.Owner)
	case *Request_Depot:
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Depot)))
		n += len(x.Depot)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Hunk struct {
	Filename         string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	StartOffset      int32  `protobuf:"varint,2,opt,name=startOffset" json:"startOffset,omitempty"`
	EndOffset        int32  `protobuf:"varint,3,opt,name=endOffset" json:"endOffset,omitempty"`
	SRC              string `protobuf:"bytes,4,opt,name=SRC" json:"SRC,omitempty"`
	DecoratorOptions string `protobuf:"bytes,5,opt,name=decoratorOptions" json:"decoratorOptions,omitempty"`
	IsHeartbeat      bool   `protobuf:"varint,6,opt,name=isHeartbeat" json:"isHeartbeat,omitempty"`
}

func (m *Hunk) Reset()                    { *m = Hunk{} }
func (m *Hunk) String() string            { return proto.CompactTextString(m) }
func (*Hunk) ProtoMessage()               {}
func (*Hunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Request)(nil), "rpc.Request")
	proto.RegisterType((*Hunk)(nil), "rpc.Hunk")
}

func init() {
	proto.RegisterFile("github.com/codelingo/codelingo/flows/codelingo/rewrite/rpc/rewrite.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x8a, 0xdb, 0x30,
	0x10, 0xc6, 0xeb, 0x38, 0x7f, 0xb5, 0x7f, 0x58, 0x44, 0x29, 0xa2, 0xf4, 0x60, 0x96, 0x1e, 0x42,
	0x0f, 0xde, 0x43, 0xdf, 0x20, 0xd9, 0x43, 0x0a, 0x0b, 0x09, 0xea, 0xa1, 0x67, 0x47, 0x1a, 0xc7,
	0xa2, 0x5e, 0x8f, 0x2a, 0xc9, 0x9b, 0xf7, 0xe9, 0xa3, 0x14, 0xfa, 0x5e, 0x65, 0x64, 0x3b, 0xeb,
	0xa5, 0x27, 0x7f, 0xdf, 0x4f, 0xc3, 0x8c, 0xe7, 0x63, 0xd8, 0xee, 0x64, 0x42, 0xd5, 0x1e, 0x73,
	0x85, 0xcf, 0x0f, 0x0a, 0x35, 0xd4, 0xa6, 0x39, 0xe1, 0x48, 0x95, 0x35, 0x9e, 0xfd, 0xc8, 0x3b,
	0x38, 0x3b, 0x13, 0xe0, 0xc1, 0x59, 0x35, 0xe8, 0xdc, 0x3a, 0x0c, 0xc8, 0x53, 0x67, 0xd5, 0xfd,
	0xdf, 0x09, 0x5b, 0x48, 0xf8, 0xd5, 0x82, 0x0f, 0x9c, 0xb3, 0x69, 0x85, 0x3e, 0x88, 0x24, 0x4b,
	0xd6, 0x2b, 0x19, 0x35, 0xff, 0xc8, 0x96, 0xf4, 0x6d, 0x8a, 0x67, 0x10, 0x93, 0xc8, 0x2f, 0x9e,
	0x7f, 0x60, 0x33, 0x3c, 0x37, 0xe0, 0xc4, 0x35, 0x3d, 0xec, 0xde, 0xc9, 0xce, 0x12, 0xd7, 0x60,
	0x31, 0x88, 0x9b, 0x81, 0x47, 0x4b, 0xfd, 0x1d, 0x58, 0x14, 0xd3, 0xae, 0x3f, 0x69, 0x7e, 0xc7,
	0x52, 0x5f, 0x15, 0x62, 0x16, 0x11, 0x49, 0x2e, 0xd8, 0xe2, 0x50, 0x04, 0x55, 0x81, 0x17, 0xf3,
	0x2c, 0x5d, 0xaf, 0xe4, 0x60, 0xf9, 0x67, 0x76, 0x63, 0xfc, 0xa1, 0xad, 0xeb, 0xfe, 0x87, 0xc5,
	0x22, 0x4b, 0xd6, 0x4b, 0xf9, 0x16, 0x52, 0x95, 0x7d, 0xb5, 0xdf, 0x1e, 0xc5, 0x32, 0x4b, 0xd6,
	0xa9, 0x7c, 0x0b, 0x69, 0xee, 0x8b, 0xf2, 0x62, 0xd5, 0xcd, 0x7d, 0x51, 0x9e, 0x36, 0xd5, 0x18,
	0x62, 0x68, 0x82, 0x75, 0x9b, 0x0e, 0x9e, 0xaa, 0xb5, 0x71, 0xe2, 0xaa, 0xab, 0xd6, 0xc6, 0x6d,
	0x6e, 0xd9, 0x75, 0x5c, 0x76, 0xef, 0x1e, 0x69, 0xb7, 0xfb, 0x3f, 0x09, 0x9b, 0xee, 0xda, 0xe6,
	0x27, 0xb5, 0x29, 0x4d, 0x0d, 0x31, 0xb0, 0x2e, 0xc8, 0x8b, 0xe7, 0x19, 0xbb, 0xf2, 0xa1, 0x70,
	0x61, 0x5f, 0x96, 0x1e, 0x42, 0xcc, 0x73, 0x26, 0xc7, 0x88, 0x7f, 0x62, 0x2b, 0x68, 0x74, 0xff,
	0x9e, 0xc6, 0xf7, 0x57, 0x40, 0xbf, 0xf1, 0x5d, 0x6e, 0xfb, 0xfc, 0x48, 0xf2, 0x2f, 0xec, 0x4e,
	0x83, 0x42, 0x57, 0x04, 0x74, 0x7b, 0x1b, 0x0c, 0x36, 0xbe, 0xcf, 0xf2, 0x3f, 0x4e, 0xd3, 0x8d,
	0xdf, 0x41, 0xe1, 0xc2, 0x11, 0x8a, 0x20, 0xe6, 0x31, 0xbc, 0x31, 0xda, 0xe4, 0xec, 0xbd, 0xc1,
	0xfc, 0x72, 0x3b, 0xf9, 0xc9, 0x59, 0x95, 0xab, 0x7a, 0x73, 0xbb, 0x45, 0x0d, 0x4f, 0x84, 0x0e,
	0x74, 0x39, 0x87, 0xe4, 0xf7, 0x24, 0xdd, 0x3e, 0xfd, 0x38, 0xce, 0xe3, 0x21, 0x7d, 0xfd, 0x17,
	0x00, 0x00, 0xff, 0xff, 0xa1, 0x75, 0xdc, 0xcd, 0x94, 0x02, 0x00, 0x00,
}
